# Generated by Django 5.2.8 on 2025-11-08 20:35

import django.db.models.deletion
import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Municipality',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'Municipality',
            },
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'Pais',
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('legal_id', models.CharField(max_length=250)),
                ('email_admin', models.CharField(max_length=250)),
                ('phone', models.CharField(max_length=100)),
                ('street_num', models.CharField(max_length=250)),
                ('muni', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='register_clients.municipality')),
            ],
            options={
                'db_table': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='regiones', to='register_clients.pais')),
            ],
            options={
                'db_table': 'Region',
            },
        ),
        migrations.AddField(
            model_name='municipality',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='municipalidades', to='register_clients.region'),
        ),
    ]
