# Generated by Django 5.2.8 on 2025-11-08 22:38

import django.db.models.deletion
import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register_clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'Industry',
            },
        ),
        migrations.AddField(
            model_name='cliente',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='register_clients.pais'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='industry',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='register_clients.region'),
        ),
        migrations.AddField(
            model_name='pais',
            name='code',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='muni',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='register_clients.municipality'),
        ),
    ]
