# Generated by Django 5.2.8 on 2025-11-09 07:53

import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register_clients', '0002_industry_cliente_country_cliente_industry_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('value', models.DecimalField(decimal_places=2, max_digits=9)),
            ],
            options={
                'db_table': 'Plan',
            },
        ),
    ]
