# Generated by Django 5.2.8 on 2025-11-17 15:26

import django.db.models.deletion
import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register_clients', '0004_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Whatsapp',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=250)),
                ('email_fb', models.CharField(max_length=250)),
                ('pass_fb', models.CharField(max_length=250)),
                ('id_app_fb', models.CharField(max_length=250)),
                ('secret_pass_app_fb', models.CharField(max_length=250)),
                ('token_user_fb', models.CharField(max_length=250)),
                ('business_acount_id', models.CharField(max_length=250)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_accounts', to='register_clients.cliente')),
            ],
            options={
                'db_table': 'Whatsapp',
            },
        ),
    ]
