# Generated by Django 5.2.8 on 2025-11-17 19:10

import django.db.models.deletion
import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register_clients', '0005_whatsapp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=250)),
                ('chat', models.TextField(blank=True, null=True)),
                ('whatsapp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chats_whatsapp', to='register_clients.whatsapp')),
            ],
            options={
                'db_table': 'Chat_whatsapp',
            },
        ),
    ]
