# Generated by Django 5.2.8 on 2025-11-18 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register_clients', '0006_chat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='chat',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='company_name',
        ),
        migrations.AddField(
            model_name='chat',
            name='messages',
            field=models.JSONField(blank=True, default=list, help_text='Chats from whatsapp', null=True),
        ),
        migrations.AddField(
            model_name='chat',
            name='sessionID',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
