# Generated by Django 5.2.8 on 2025-11-18 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register_clients', '0007_remove_chat_chat_remove_chat_company_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chat',
            options={'managed': False},
        ),
    ]
