# Generated by Django 5.2.8 on 2025-11-26 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register_clients', '0008_alter_chat_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='cliente',
            new_name='empresa',
        ),
    ]
